import React, { useState } from 'react';
import { X, Copy, Check, Printer, Download, User } from 'lucide-react';
import Button from '../ui/Button';

export default function SuccessModal({ mechanic, tempPassword, onClose, onResetPassword }) {
  const [copied, setCopied] = useState(false);

  const credentials = `Mechanic ID: ${mechanic.id}\nUsername: ${mechanic.username}\nTemporary Password: ${tempPassword}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(credentials).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>Mechanic Credentials</title>
      <style>body{font-family:system-ui;padding:40px;max-width:500px;margin:auto}
      h2{color:#0F2A4A}table{width:100%;border-collapse:collapse;margin-top:20px}
      td{padding:10px;border-bottom:1px solid #eee}td:first-child{font-weight:600;color:#64748B;width:180px}
      .badge{background:#EFF6FF;color:#2563EB;padding:6px 12px;border-radius:8px;display:inline-block;font-weight:700;font-size:1.1em}
      footer{margin-top:40px;font-size:12px;color:#94a3b8}</style></head>
      <body>
        <h2>✅ Mechanic Created Successfully</h2>
        <p style="color:#64748B">Please share these credentials securely with the mechanic.</p>
        <table>
          <tr><td>Mechanic ID</td><td><span class="badge">${mechanic.id}</span></td></tr>
          <tr><td>Full Name</td><td>${mechanic.name}</td></tr>
          <tr><td>Username</td><td>${mechanic.username}</td></tr>
          <tr><td>Temp Password</td><td><code style="background:#f1f5f9;padding:2px 8px;border-radius:4px">${tempPassword}</code></td></tr>
          <tr><td>Email</td><td>${mechanic.email}</td></tr>
          <tr><td>Phone</td><td>${mechanic.phone}</td></tr>
        </table>
        <footer>Generated by BikeCare Connect — ${new Date().toLocaleString()}</footer>
      </body></html>
    `);
    win.print();
    win.close();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)' }}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-modal-enter">
        {/* Header */}
        <div className="bg-gradient-to-r from-green-500 to-emerald-600 p-6 text-white relative">
          <button onClick={onClose} className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-full bg-white/20 hover:bg-white/30 transition-colors">
            <X size={16} color="white" />
          </button>
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
              <User size={24} color="white" />
            </div>
            <div>
              <h2 className="text-lg font-bold">Mechanic Created!</h2>
              <p className="text-green-100 text-sm">Credentials generated successfully</p>
            </div>
          </div>
        </div>

        {/* Body */}
        <div className="p-6">
          {/* Credential rows */}
          <div className="space-y-3 mb-5">
            <CredRow label="Mechanic ID" value={mechanic.id} highlight />
            <CredRow label="Full Name" value={mechanic.name} />
            <CredRow label="Username" value={mechanic.username} />
            <CredRow label="Temp Password" value={tempPassword} mono />
            <CredRow label="Email" value={mechanic.email} />
            <CredRow label="Phone" value={mechanic.phone} />
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 mb-5">
            <p className="text-amber-700 text-xs font-medium">⚠️ Share these credentials securely. The mechanic should change their password on first login.</p>
          </div>

          {/* Actions */}
          <div className="grid grid-cols-2 gap-2">
            <Button variant="outline" onClick={handleCopy} className="justify-center">
              {copied ? <Check size={14} className="text-green-600" /> : <Copy size={14} />}
              {copied ? 'Copied!' : 'Copy Credentials'}
            </Button>
            <Button variant="outline" onClick={handlePrint} className="justify-center">
              <Printer size={14} /> Print
            </Button>
          </div>
          <Button variant="accent" className="w-full justify-center mt-2" onClick={onClose}>
            Done
          </Button>
        </div>
      </div>
    </div>
  );
}

function CredRow({ label, value, highlight, mono }) {
  return (
    <div className="flex items-center justify-between py-2 border-b border-border/60">
      <span className="text-xs font-semibold text-text-secondary uppercase tracking-wide">{label}</span>
      <span className={`text-sm font-semibold ${highlight ? 'text-accent bg-blue-50 px-2 py-0.5 rounded-lg' : 'text-text-primary'} ${mono ? 'font-mono bg-slate-100 px-2 py-0.5 rounded-md' : ''}`}>
        {value}
      </span>
    </div>
  );
}
